server:
  port: 5004

spring:
  application:
    name: service-offering

  datasource:
    url: jdbc:mysql://localhost:3306/serviceofferingdb_salonsync?createDatabaseIfNotExist=true
    username: root
    password: 123@idr
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: "http://localhost:8070/eureka/"
