server:
  port: 5007

spring:
  application:
    name: notification-service

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/notificationdb_salonsync?createDatabaseIfNotExist=true
    username: root
    password: 123@idr
    driver-class-name: com.mysql.cj.jdbc.Driver

  rabbitmq:
    port: 5672
    host: rabbit
    username: guest
    password: guest

  eureka:
    instance:
      prefer-ip-address: true
    client:
      fetch-registry: true
      register-with-eureka: true
      service-url:
        defaultZone: "http://localhost:8070/eureka/"



